
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jpaMysql_dev
    username: root
    password: Alslehfk1@
    driver-class-name: com.mysql.cj.jdbc.Driver

#    H2쓰는경우
#    url: jdbc:h2:./sb_23_11_27_dev;MODE=MySQL
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
logging:
  level:
    com.ll.springjpaquerydsl: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.orm.jdbc.extract: TRACE
    org.springframework.transaction.interceptor: TRACE